### ISSUE TITLE
Bug with Numpy 1.19.4 and Python 3.8.6

### ISSUE THREAD

**Issue by mariusCZ** [GCBallesteros/MeepTutorials#1]
Hello,

Not sure if this is still maintained, but want to report a bug.

Line 65: `freqs = np.fft.fftfreq(n_sample_points, d=dt)[:(n_sample_points/2)]`

Throws error: `TypeError: slice indices must be integers or None or have an __index__ method`

Can be fixed by changing Line 65 to `freqs = np.fft.fftfreq(n_sample_points, d=dt)[:(int(n_sample_points/2))]`

The issue arises due to the division by 2 causing the number to become a float, even if it is an even number.

**Comment by GCBallesteros** [comment]
Thanks @mariswow ! Do you want to put in a pull request. I will do the fixing otherwise. Best Guillem.

**Comment by mariusCZ** [comment]
Pull request posted.

I will likely be using the frequency monitor quite extensively and will be adding some improvements. If you would like, I can keep posting pull requests for added functionalities.

**Comment by GCBallesteros** [comment]
I'm not longer into the business of running simulations but please feel free to send in pull requests. Hopefully, they will make things easier for somebody else out there. Will update the blog post to give you attribution when I have some time.

Thanks!

**Comment by mariusCZ** [comment]
#2 Merge fixes the issue.
